baseURL = 'https://bergen-road-trips.org'
languageCode = 'en-us'
title = 'Bergen Road Trips'
theme = 'hugo-theme-stack'

# # config.toml
# [[module.imports]]
# path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[params]
favicon = "/favicon.ico" # Path to favicon file